global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ml-api'
    static_configs:
      - targets: ['api:8001']
    scrape_interval: 5s
    metrics_path: '/metrics/prometheus'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']